CREATE DATABASE MARTA_GULIDA;

USE MARTA_GULIDA;
GO

CREATE SCHEMA sales;
GO

CREATE SCHEMA persons;
GO

CREATE TABLE sales.Orders (OrderNum INT NULL);
GO

BACKUP DATABASE MARTA_GULIDA
TO DISK = 'D:\db-part-2\lab1\MARTA_GULIDA.bak';
GO

DROP DATABASE MARTA_GULIDA;
GO

RESTORE DATABASE MARTA_GULIDA
  FROM DISK = 'D:\db-part-2\lab1\MARTA_GULIDA.bak';
GO